= Metanorma sample documents for M3AAWG (Metanorma-M3D)

image:https://github.com/metanorma/mn-samples-m3aawg/workflows/generate/badge.svg["Ubuntu Build Status", link="https://github.com/metanorma/mn-samples-m3aawg/actions?query=workflow%3Agenerate"]
image:https://github.com/metanorma/mn-samples-m3aawg/workflows/docker/badge.svg["Docker Build Status", link="https://github.com/metanorma/mn-samples-m3aawg/actions?query=workflow%3Adocker"]

This document is available in its rendered forms here:

* https://metanorma.github.io/mn-samples-m3aawg/[M3AAWG samples]

== Introduction

This repository provides readily usable https://github.com/metanorma/metanorma-m3aawg[Metanorma-M3AAWG]
sample documents.

Refer to the https://www.metanorma.com/overview/getting-started/[Metanorma quickstart] for a primer on creating Metanorma-M3AAWG documents.


== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/mn-samples-m3aawg/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate . -o published -c metanorma.yml
----


== Building The Document

[source,sh]
----
metanorma site generate . -o published -c metanorma.yml
----


== Source files provided in this repo

* `best-practice/best-practice.adoc`: M3AAWG Best Practice document, based on the CalConnect CalSpam document.
